### ISSUE TITLE
lock is not released

### ISSUE THREAD

**Issue by moskvich412** [tiian/flom#11]
Situation: FLoM is used to manage access to a file. The actual commands mostly read the file and sometimes update it. Each takes milliseconds.

Symptom: File is not updated for hours. File became empty (not sure yet how this is possible). When file is empty, the commands managed by FLoM should simply exit. This means, the resource is always available. Instead, FLoM locked the resource and does not give it to any commands. They terminate on FLoM timeout. 

FLoM daemon did not die. Access to other similar files with similar commands is OK.

**Comment by tiian** [comment]
From the above narrative is quite complex, maybe impossible to catch the "issue".
All the below possible issues are compatible with the behaviour you are describing:

- for some reason, the flom client does not intercept the command termination
- a network partition between the flom client and the flom daemon happens and for some reason nor the client, neither the daemon, detect the network partition
- for some reason, the flom daemon does not detach the flom client

All the above situations can be debugged with proper trace flags: the technique is always the same

- take a look to file src/flom_trace.h , the comments should be self explanatory
- detect the module(s) you want to trace
- use boolean and operator among all the value you want
- set the FLOM_TRACE_MASK env var
- if necessary use -t and -T flags to redirect the trace (quite mandatory to catch daemon messages)

**Comment by moskvich412** [comment]
I agree I gave  vague description, I do not know what else to add. I will try your suggestions.

The issue could also be related to issue 10, when I inadvertently used hierarchical resource instead of simple.

**Comment by tiian** [comment]
No enough info to consider it a real issue. If any, please re-open with more specific description.
