### ISSUE TITLE
Lock mode ProtectedWrite misinterpreted as ProtectedRead in the CLI parser

### ISSUE THREAD

**Issue by karelklic** [tiian/flom#13]
Hello,
FLoM's command line parser misinterprets ProtectedWrite lock mode as ProtectedRead.

The code in flom_msg.c catches the first two letters ("Pr") of the ProtectedWrite argument when locating PR substring in the `if (NULL != (p = STRCASESTR(text, "PR")))` code which handles the ProtectedRead lock mode.

Perhaps the solution would be to check ProtectedWrite and PW options before ProtectedRead and PR.

**Comment by tiian** [comment]
Many thanks!
I have never recognized that "PR" is even prefix of "PRotectedWrite".
Your proposed patch is very cute and avoid disruption of users' scripts: maybe someone around the world is using something like "-l PROTECTEDread" and forcing case sensitive at version 1.4 would be not nice for those users.
Commit b09a7e0395e69da66ded97aeee5107c5dc2e14f4 provides a temporary patch: a new release with the patch is in progress.

**Comment by tiian** [comment]
Release 1.4.3 fixes the bug.

**Comment by karelklic** [comment]
Thank you.
