### ISSUE TITLE
Lock is released when FLoM client is terminated but subprocess keeps running

### ISSUE THREAD

**Issue by karelklic** [tiian/flom#15]
When a FLoM client is terminated by a SIGTERM signal, it releases the lock it holds. However, the client's subprocess keeps running and keeps accessing the now-unprotected resource.

Here is an example:
```shell
# Start a local server.
$ ./flom --daemon-lifespan=-1 -- true

# Start two clients that try to access a single resource.
# Get their process ids.
$ ./flom --resource-name /singlebed --lock-mode PW -- sleep 1d &
[1] 11737
$ ./flom --resource-name /singlebed --lock-mode PW -- sleep 2d &
[2] 11794

# Check that only one client acquired the lock.
# Resource is now used by a subprocess.
$ ps ux | grep sleep
karel    11760  0.0  0.0 107956   616 pts/5    S    00:20   0:00 sleep 1d

# Now terminate the client currently accessing the resource.
$ kill 11737
[1]-  Terminated  ./flom --resource-name /singlebed --lock-mode PW -- sleep 1d

# Invalid state: two subprocesses are accessing a single resource in write mode.
$ ps ux | grep sleep
karel    11760  0.0  0.0 107956   616 pts/5    S    00:20   0:00 sleep 1d
karel    12990  0.0  0.0 107956   612 pts/5    S    00:21   0:00 sleep 2d
```

(I work around the issue by signal redirection as described in #14.)

**Comment by tiian** [comment]
I confirm the behaviour that's described above: it happens with and without the & (detach from terminal).
I will work on it, but not immediately.

**Comment by tiian** [comment]
Here are some notes that I have collected after some research.
FLoM client preserves the Process Group ID: both the flom client command and the monitored command are part of the same process group:

    flom --daemon-lifespan=-1 -- true
    flom --resource-name /singlebed --lock-mode PW -- sleep 1d &[1] 1160
    ps j -A | grep 'flom\|sleep\|PGID' | grep -v grep
     PPID   PID  PGID   SID TTY      TPGID STAT   UID   TIME COMMAND
        1  1157  1156  1156 ?           -1 Sl    1000   0:00 flom --daemon-lifespan=-1 -- true
     1129  1160  1160  1129 pts/0     1175 S     1000   0:00 flom --resource-name /singlebed --lock-mode PW -- sleep 1d
     1160  1162  1160  1129 pts/0     1175 S     1000   0:00 sleep 1d

sending kill to the group instead of the process, as explained [here](http://morningcoffee.io/killing-a-process-and-all-of-its-descendants.html), works fine:

    kill -SIGTERM -- -1160
    ps j -A | grep 'flom\|sleep\|PGID' | grep -v grep
     PPID   PID  PGID   SID TTY      TPGID STAT   UID   TIME COMMAND
        1  1157  1156  1156 ?           -1 Sl    1000   0:00 flom --daemon-lifespan=-1 -- true

The point is not academic because from this document, it seems that Jenkins kills all the processes of the group and not only the spawn child:

https://gist.github.com/datagrok/dfe9604cb907523f4a2f
> When a Jenkins job is cancelled, it sends TERM to the process group of the process it spawns, and immediately disconnects, reporting "Finished: ABORTED," regardless of the state of the job.

I'm neither a Jenkins expert nor a Jenkins user, but it seems that an educated way to terminate all the children exists natively in the POSIX standard.

Further reading about Process Groups is available [here](https://www.usna.edu/Users/cs/aviv/classes/ic221/s16/lec/17/lec.html)

**Comment by karelklic** [comment]
The order of termination is essential too. While FLoM client terminates quickly on SIGTERM, many apps perform cleanup, which might take a couple of seconds, such as finishing a network operation, deleting files, or some rollback. The lock should be held during the cleanup as well.

**Comment by tiian** [comment]
This is cute remark: signals to a group of process do not take care of such a behaviour.

Can we describe the issue with these words: _"Jenkins send SIGTERM to the group of processes initiated by the flom client: both the flom client and the monitored process receive SIGTERM. It can happen that flom client ends before the monitored process: sometimes the lock is released before the monitored process ends and in this case the serialized resource can be accessed by another process managed by another flom client"_ ?

**Comment by karelklic** [comment]
Yes, your description is correct.
I can confirm that Jenkins sends SIGTERM to both FLoM client and its subprocess. It behaves consistently also when multiple FLoM clients are used to get locks before starting a subprocess:
```
flom --resource-name /oneresource --lock-mode ProtectedWrite -- \
    flom --resource-name /anotherresource --lock-mode ProtectedRead -- \
        sleep 1d
```
In this case, the two FLoM clients and also the sleep subprocess receive SIGTERM when the Jenkins job is canceled.
So it's only the order of termination that is causing the resource conflict.

**Comment by tiian** [comment]
Commit cf45bd1976b019c8ff7ac21380ad22f7cb2c8beb contains an initial patch to support the new feature.

**Please pay attention it disables SIGTERM only for the time the FLoM client monitors the monitored command. The feature WILL BE enriched by command line option, but this is just to check the idea works**.

Here's what happens:

    tiian@ubuntu1004:~$ flom -- sleep 1d
    2020-02-09 12:38:03.719753 [20143/0x1f494c0] flom_exec
    2020-02-09 12:38:03.719895 [20143/0x1f494c0] flom_exec-father: child pid=20148
    2020-02-09 12:38:03.719909 [20143/0x1f494c0] flom_exec-father: waiting child termination
    2020-02-09 12:38:03.719924 [20148/0x1f494c0] flom_exec-child: command_argv[0]='sleep'
    2020-02-09 12:38:03.719968 [20148/0x1f494c0] flom_exec-child: command_argv[1]='1d'
    2020-02-09 12:38:03.719996 [20148/0x1f494c0] flom_exec-child: path='sleep'
    2020-02-09 12:38:03.720001 [20148/0x1f494c0] flom_exec-child: argv[0]='sleep'
    2020-02-09 12:38:03.720004 [20148/0x1f494c0] flom_exec-child: argv[1]='1d'
    2020-02-09 12:38:19.945386 [20143/0x1f494c0] flom_exec-father: child exit status is 0
    Terminated


    tiian@ubuntu1004:~$ ps j -A | grep 'flom\|sleep\|PGID' | grep -v grep
     PPID   PID  PGID   SID TTY      TPGID STAT   UID   TIME COMMAND
     1522 20143 20143  1522 pts/2    20143 S+    1000   0:00 flom -- sleep 1d
        1 20146 20145 20145 ?           -1 Sl    1000   0:00 flom -- sleep 1d
    20143 20148 20143  1522 pts/2    20143 S+    1000   0:00 sleep 1d
    tiian@ubuntu1004:~$ kill -SIGTERM -- -20143

The trace "flom_exec-father: child exit status is 0" shows that the FLoM client ignored the SIGTERM signal that was sent to its group.

Please check it to see if it works for you, but please pay attention it's **work in progress** source code.

**Comment by karelklic** [comment]
Thank you. I've deployed FLoM with your change to our Jenkins instance.
I'll now try to break locking via job termination in the next couple of days.

**Comment by tiian** [comment]
Do you have any feedback about the patch?

**Comment by karelklic** [comment]
The patched FLoM works fine as far as I can tell. I terminated jobs running code under a write lock here and there and encountered no issues at all.

Adding the signalignore config option to /etc/flom.conf would be very handy - I wouldn't need to modify ~130 places with the flom calls then.

**Comment by tiian** [comment]
I'm going to release a full feature in next testing release 1.5.0: it will be configurable both from command line and from configuration file.
What's your distribution, what distributions would be more appropriate to test, choosing from https://github.com/tiian/flom/blob/master/TestLog ?
I don't perform the full cycle on all the distros for testing releases.

**Comment by karelklic** [comment]
It's CentOS 7.7 x86_64 everywhere.

**Comment by tiian** [comment]
Commit bdc1009a25a896f69a4f88b1c5afbeca96075f05 is a technical preview of the new feature.
Here is the new behavior:

    tiian@ubuntu1004:~$ flom --ignore-signal=SIGTERM --resource-name /singlebed --lock-mode PW -- sleep 1d &
    [1] 14873
    tiian@ubuntu1004:~$ ps j -A | grep 'flom\|sleep\|PGID' | grep -v grep
     PPID   PID  PGID   SID TTY      TPGID STAT   UID   TIME COMMAND
        1 14867 14866 14866 ?           -1 Sl    1000   0:00 flom --daemon-lifespan=-1 -- true
     3676 14873 14873  3676 pts/2    14876 S     1000   0:00 flom --ignore-signal=SIGTERM --resource-name /singlebed --lock-mode PW -- sleep 1d
    14873 14875 14873  3676 pts/2    14876 S     1000   0:00 sleep 1d
    tiian@ubuntu1004:~$ kill -SIGTERM -- -14873
    tiian@ubuntu1004:~$ 
    [1]+  Done                    flom --ignore-signal=SIGTERM --resource-name /singlebed --lock-mode PW -- sleep 1d

and here is the old behavior (SIGDUMMY does not exists):

    tiian@ubuntu1004:~$ flom --ignore-signal=SIGDUMMY --resource-name /singlebed --lock-mode PW -- sleep 1d &
    [1] 14880
    tiian@ubuntu1004:~$ ps j -A | grep 'flom\|sleep\|PGID' | grep -v grep
     PPID   PID  PGID   SID TTY      TPGID STAT   UID   TIME COMMAND
        1 14867 14866 14866 ?           -1 Sl    1000   0:00 flom --daemon-lifespan=-1 -- true
     3676 14880 14880  3676 pts/2    14883 S     1000   0:00 flom --ignore-signal=SIGDUMMY --resource-name /singlebed --lock-mode PW -- sleep 1d
    14880 14882 14880  3676 pts/2    14883 S     1000   0:00 sleep 1d
    tiian@ubuntu1004:~$ kill -SIGTERM -- -14880
    tiian@ubuntu1004:~$ 
    [1]+  Terminated              flom --ignore-signal=SIGDUMMY --resource-name /singlebed --lock-mode PW -- sleep 1d

In the first sequence, the FLoM monitor terminates normally ("Done"), in the second sequence it's killed by the signal ("Terminated").
The new key in flom.conf is "IgnoredSignals" in section [Monitor].
Please give it a try in the meantime I do some testing.

**Comment by tiian** [comment]
Commit 0aa9ac50af1a02371a05e89b92c347c106d2401b contains some refinements in signal handling. Now ignored signals can be expressed even with numbers like `--ignore-signal=15`

**Comment by tiian** [comment]
Added [Integration](http://www.tiian.org/flom/Deep_Diving/Integrating.html) documentation page.

**Comment by tiian** [comment]
Release 1.5.19 is now available:

- it has been tested as documented in https://github.com/tiian/flom/blob/1.5.19/TestLog 

- it supports "--ignore-signal" and "--signal-list" command option
