### ISSUE TITLE
API for Python3

### ISSUE THREAD

**Issue by slberger** [tiian/flom#16]
Would love to have the flom python API available for python3. In CentOS 8.1, python3 is the default and python2 is not installed by default. In earlier versions of CentOS (7.7), python2 is the default but python3 can be installed as well. I would like to see the flom python API available for python3 in both cases. Thank you!

**Comment by tiian** [comment]
I'm going to provide support for Python 3.

**Comment by tiian** [comment]
[tiian@centos8 tmp]$ git clone https://github.com/tiian/flom.git
[tiian@centos8 tmp]$ cd flom
[tiian@centos8 flom]$ PYTHON_VERSION=3 ./configure
[tiian@centos8 flom]$ make
[tiian@centos8 flom]$ sudo make install
[tiian@centos8 flom]$ cd /usr/local/share/doc/flom/examples/python/
[tiian@centos8 python]$ flom -s /tmp/my_socket_name -d -1 -- true
[tiian@centos8 python]$ pgrep flom
8469
[tiian@centos8 python]$ python3 advanced.py 
flom_handle_lock(): locked element is 'Red'

Please consider commit 508ada820f394ceabb4a9d5e5b99372eebadb993 a very early stage.
K.R.
Ch.F.

**Comment by slberger** [comment]
Seems to work fine. Thank you very much!

**Comment by tiian** [comment]
Release 1.5.20 https://github.com/tiian/flom/tree/1.5.20 fixes the bug: please give me your feedback.

**Comment by slberger** [comment]
Works like a charm. I tested it with CentOS 7.8 and CentOS 8.1. Thank for very much for addressing this so quickly!
