### ISSUE TITLE
perl5: command not found. Build error

### ISSUE THREAD

**Issue by Tozapid** [tiian/flom#18]
Hello! When I try to build the deb package (1.5.20+), I get the following error:

```
perl5 -const -I.. flom.i
/bin/bash: perl5: command not found
```
Perl 5 is installed on the server, but has a different name

```
root@debian:/tmp/flom/flom-1.5.20# apt-cache policy perl
perl:
  Installed: 5.24.1-3+deb9u7
  Candidate: 5.24.1-3+deb9u7
  Version table:
 *** 5.24.1-3+deb9u7 500
        500 http://deb.debian.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     5.24.1-3+deb9u5 500
        500 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
```

I just solved this error by adding a symbolic link, but I think that need to add a check to the program code

**Comment by tiian** [comment]
I have reproduced the same error:

    [...]
    Makefile.PL.in >Makefile.PL
    sed \
    -e 's|@PACKAGE_VERSION[@]|1.5.21|g' \
    README.in >README
    perl5 -const -I.. flom.i
    /bin/bash: perl5: command not found
    make[4]: [Makefile:481: flom_wrap.o] Error 127 (ignored)
    sed -i 's/*flom_/*/g' Flom.pm
    sed: can't read Flom.pm: No such file or directory
    [...]

it seems correlated even with issue #17 
I have to probably fix configure.ac or something else of the GNU buildchain

**Comment by tiian** [comment]
Please look at the hint provided for issue #17 and give me a feedback

**Comment by tiian** [comment]
No provided documentation, no reason to keep it open. See #17
