### ISSUE TITLE
Build error when JDK is not available

### ISSUE THREAD

**Issue by tiian** [tiian/flom#20]
In some systems, if JDK is not available, the configure script ends with an error like:

    ...
    checking for TLSv1_method... yes
    checking for TLSv1_1_method... yes
    checking for TLSv1_2_method... yes
    checking for TLS_method... yes
    configure: error: conditional "COND_JAVADOC_HTML5" was never defined.
    Usually this means the macro was only invoked conditionally.

**Comment by tiian** [comment]
Fixed with commit ee63b16d8809fcfd671049cfc984c2274850285d

**Comment by damoclark** [comment]
For CentOS 7, the correct package is `java-1.8.0-openjdk-devel` or `java-11-openjdk-devel`. This includes the javac compiler, unlike `java-1.8.0-openjdk` which is included in https://github.com/tiian/flom/commit/ee63b16d8809fcfd671049cfc984c2274850285d
