### ISSUE TITLE
Use Case: "replace" first job after timeout ?

### ISSUE THREAD

**Issue by aadrian** [tiian/flom#23]
Hi,

Is the following Use Case already covered ?:

Use Case 4, with timeout https://www.tiian.org/flom/FLoM_by_examples/Use_Case_4.html , but 
 - instead of the second job failing after a timeout: just replace/kill the first job and than only execute the second job ?

Thank you.

**Comment by tiian** [comment]
Hi Adrian,
the answer to your question is "no", flom does not kill a job to start another one competing for the same resource, this is not a directly supported use case.

But, there's a but: flom is a command line tool that you can integrate in your own custom logic.
In the event of timeout, the command exits with a special exit code as shown below:

    tiian@ubuntu1004:~$ flom --resource-timeout=1000 -- ls
    The lock was not obtained because timeout (1000 milliseconds) expired
    tiian@ubuntu1004:~$ echo $?
    98

98 is the value assigned to macro FLOM_ES_RESOURCE_BUSY that's defined as

    _ES_RESOURCE_BUSY=98

in file configure.ac

At the end of the day, you can wrap the flom command in your own script that recognize the FLOM_ES_RESOURCE_BUSY condition, kill the first job, submit again the second job.

I have no idea what does it mean, in terms of use case and side effects, implementing it directly in "flom"...
Can you elaborate a little bit "why" and "where" do you need such use case?

**Comment by tiian** [comment]
No further feedback from the user.
