### ISSUE TITLE
Unsetting configuration parameters from config files

### ISSUE THREAD

**Issue by damoclark** [tiian/flom#25]
Hi Christian,

Thanks for sharing your work on Flom through an open licence.  I work for a University and used it circa 2014 until recently for research and educational technology supporting students.  It worked flawlessly.  I also read your 2016 paper on Flom.  Really nice work. :)

I'm now using Flom for a personal project and have come across a small challenge related to the configuration file processing.  

I have a series of shell commands I am attempting to synchronise utilising combinations of multiple local and network resources.  More specifically, I am co-ordinating distributed backups using a tool called [Restic](https://github.com/restic/restic).  The backups occur on multiple hosts, and comprise of a range of 'jobs' that require either CW, CR or EX locking semantics.  Furthermore, I'm also attempting to limit the number of concurrent tasks that backup to single host at a time (numeric resource), and limit the number of concurrent tasks that execute locally on each host (second numeric resource).  The tasks include backup, pruning, checking and others.  Thus, a distributed environment, with deterministic load and sequencing of these tasks is required.  Restic itself performs locking, but it doesn't block/queue (nor can it, with its design goal).

With the context set, the issue I seem to 'but up' against, is having flom config files that allow flom to run both locally, and as a client to a central network daemon.  

In my `/usr/local/etc/flom.conf` file on all my hosts, I have specified the Unicast IP address of my locking daemon.  I can invoke `flom` without any commandline arguments apart from resource & lockmode, which is really nice and simple.  To execute flom using only local locks, I have attempted to switch from Unicast IP to a local Unix socket file.  I tried to specify this on the command line, but flom errors that it is invalid config to have both network and socket modes.  So I attempted to use a separate config file with the socketfile set, and specify this separate config file using `-c` option.  But it appears that flom always reads the `/usr/local/etc/flom.conf` global config file, and merges changes with the `-c` one.  So then I attempted to 'unset' the Unicast IP address in my `-c` config file as `UnicastAddress=`.  But config validation says `flom_client_connect: ret_cod=-109 (ERROR: 'getaddrinfo' function returned an error condition)`, presumably because the value is an empty string and not resolvable.

So, I'm a little stymied.  I had considered using the unicast IP daemon with a numeric resource name specific to each host (i.e. hostname) to perform locks locally, but I had hoped to avoid that.  

Have I overlooked a configuration approach to 'disable' previously configured settings?  Or is there another way apart from using distributed lock daemon for local locking?

Thanks again Christian.

Cheers,
Damien.

**Comment by tiian** [comment]
Hi Damien,
I confirm the behavior you explained: FLoM currently managed the 3 levels of configuration:

- /usr/local/etc/flom.conf
- ~/.flom
- command line parameters

using a pure additional approach: options are added / replaced from one level to the other, but not removed.
You can figure out better how it works setting environment variable 

    export FLOM_TRACE_MASK=0x2

to get configuration tracing.

Depending on your configuration some available alternatives are below:

if remote tasks are executed from usera and local tasks are executed from userb you can:

- centralize all the options but the unicast / local socket in /usr/local/etc/flom.conf
- create /home/usera/.flom with only unicast
- create /home/userb/.flom with only local socket

if both local and remote tasks are executed with the same user you can:

- centralize all the options but the unicast / local socket in /usr/local/etc/flom.conf
- specify the unicast/local socket option on the command line

but there's another "smart trick":

- use only unicast, even for local task
- use different resources, one for every system, to avoid collision, but a single central daemon

How to create different resources without risking name clashing?
FLoM can help with "--unique-id" option, here is a trivial example:

    flom --resource-name=R$(flom --unique-id) -- ls

use a resource with name R91ed6d1ed76c5773c7503d285679b33b
for a simple resource, but if you need another resource type, just hack a little of shell expansion to get what you want.

Maybe other alternatives could exist, but the 3 I have described above are the first coming to my mind... Could be some user can provide other smart ideas.

In the end, the behavior you expected would be "elegant and reasonable" in your specific case, but introducing that additional logic might generate some "strange behavior somewhere else" or at least would require accurate thinking to avoid breaking running configurations.

Let me know if it helps for you.
Best
Christian

**Comment by tiian** [comment]
Of course, there's even a straighforward configuration based on:

- all the common non default configurations in /usr/local/etc/flom.conf
- one config file with the only local socket configuration, to be used with a -c on the command line
- one config file with the only network socket configuration, to be used with a -c con the command line

Best
Christian
