### ISSUE TITLE
build fails in non-networked environments

### ISSUE THREAD

**Issue by andreasstieger** [tiian/flom#27]
`configure.ac` attempts to detect a network interface during build. This breaks the build in non-networked environments, in particular build environment of distributions. I disabled this part entirely `sed -i -e '/find a valid network interface/,+15d' configure`

Please support builds entirely offline. This is for the openSUSE rpm.

**Comment by tiian** [comment]
The attempts to detect a network interface is necessary to prepare the scripts to run "make check", but I understand that this "battery included" behavior is not desirable for building an rpm.

If I implemented an option like "--disable-testcases"

    ./configure --disable-testcases

would it be a viable solution for you?

**Comment by andreasstieger** [comment]
Yes that would be fine. In case you have test case that make sense without network you could split them from those needing a network interface.

**Comment by tiian** [comment]
> Yes that would be fine. In case you have test case that make sense without network you could split them from those needing a network interface.

I'm working on it, but I keep my time because it's easy to break automake/autoconf toolchain.

**Comment by tiian** [comment]
Added commit 19def10ebd267b6167e196e1afee857c2102faf9 to support 

     ./configure --disable-testcases

In case you need a tarball, you can produce it using "make dist".
Please try if it works for you.

**Comment by andreasstieger** [comment]
unable due to other build system related issues. I'm sure it is fine, I'll pick it up on the next release

**Comment by tiian** [comment]
The new configure option is now part of release 1.6.1 https://github.com/tiian/flom/releases/tag/1.6.1
