### ISSUE TITLE
./configure: line 18715: test: -ge: unary operator expected

### ISSUE THREAD

**Issue by damoclark** [tiian/flom#31]
This error occurs when running configure, although it doesn't appear to cause any problems with the build process.  Just reporting as a low priority issue.

Tested on Ubuntu 22.04 and Debian 12.

Command:

```bash
./configure --disable-{php,perl,python,java}
```

**Comment by tiian** [comment]
Hi Damo, can you try with commit e681162018162054efcfe5368430c5293be61873 of you get the same symptoms?

**Comment by damoclark** [comment]
> Hi Damo, can you try with commit [e681162](https://github.com/tiian/flom/commit/e681162018162054efcfe5368430c5293be61873) if you get the same symptoms?

The error no longer occurs with this commit.

**Comment by tiian** [comment]
Release 1.7.2 incorporates the patches
