### ISSUE TITLE
Debian 9

### ISSUE THREAD

**Issue by Tozapid** [tiian/flom#8]
Hello! I Can't use flom with Debian 9 because it don't have libssl1.0.0.

Only libssl1.0.2 and libssl1.1 .

Can you update flom for use new librares?

**Comment by tiian** [comment]
Dear Tozapid,
thank you for signalling me the issue.
I'm currently very busy on [LIXA](http://www.tiian.org/lixa/) project and I have no time to fix it immediately.
A feasible time-frame could be the planned update for Ubuntu 18.04.
In the meantime, any fix proposal will be welcome.
Kind Regards
Ch.F.

**Comment by tiian** [comment]
Release 1.4.0, commit f6af7e462df2ba0fb4f352b1bfa055a5a15b1d4a solves the issue on Ubuntu 18.04 and should solve it even for Debian 9.
